---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - catrdg.cnri.platform
  resources:
  - cartridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catrdg.cnri.platform
  resources:
  - cartridges/finalizers
  verbs:
  - update
- apiGroups:
  - catrdg.cnri.platform
  resources:
  - cartridges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeovn.io
  resources:
  - subnets
  - vpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances/status
  - virtualmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - simreq.cnri.platform
  resources:
  - simrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simreq.cnri.platform
  resources:
  - simrequests/finalizers
  verbs:
  - update
- apiGroups:
  - simreq.cnri.platform
  resources:
  - simrequests/status
  verbs:
  - get
  - patch
  - update
